<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'apimatic\\jsonmapper\\' => array($vendorDir . '/apimatic/jsonmapper/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Mundipagg\\Magento\\' => array($baseDir . '/app/code/community/Mundipagg/Paymentmodule'),
    'Mundipagg\\Core\\Test\\' => array($vendorDir . '/mundipagg/ecommerce-module-core/tests'),
    'Mundipagg\\Core\\' => array($vendorDir . '/mundipagg/ecommerce-module-core/src'),
    'Mundipagg\\' => array($baseDir . '/app'),
    'MundiAPILib\\' => array($vendorDir . '/mundipagg/mundiapi/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
