<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit53393b2b85232508b6a50e8fba4a43c4
{
    public static $prefixLengthsPsr4 = array (
        'a' => 
        array (
            'apimatic\\jsonmapper\\' => 20,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Mundipagg\\Magento\\' => 18,
            'Mundipagg\\Core\\Test\\' => 20,
            'Mundipagg\\Core\\' => 15,
            'Mundipagg\\' => 10,
            'MundiAPILib\\' => 12,
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'apimatic\\jsonmapper\\' => 
        array (
            0 => __DIR__ . '/..' . '/apimatic/jsonmapper/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Mundipagg\\Magento\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/code/community/Mundipagg/Paymentmodule',
        ),
        'Mundipagg\\Core\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/mundipagg/ecommerce-module-core/tests',
        ),
        'Mundipagg\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/mundipagg/ecommerce-module-core/src',
        ),
        'Mundipagg\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
        'MundiAPILib\\' => 
        array (
            0 => __DIR__ . '/..' . '/mundipagg/mundiapi/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'Unirest\\' => 
            array (
                0 => __DIR__ . '/..' . '/mashape/unirest-php/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit53393b2b85232508b6a50e8fba4a43c4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit53393b2b85232508b6a50e8fba4a43c4::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit53393b2b85232508b6a50e8fba4a43c4::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
