
<?php echo $this->getCssJsHtml(); ?>

<script>
    jQuery(document).ready(function()
    {
        window.mundipagg_skin_base_url = '<?php echo $this->getSkinUrl(''); ?>';
        window.mundipagg_base_url = '<?php echo $this->getStoreUrl(); ?>';
        window.mundipagg_hub_validate = '<?php echo $this->getHubValidateUrl(); ?>';
        window.mundipagg_hub_status = '<?php echo $this->getHubStatusUrl(); ?>';
        window.mundipagg_hub_generate_integration = '<?php echo $this->getHubGenerateIntegrationUrl(); ?>';
    });
</script>