<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Geoip
 */
?>
<br/> <?php echo $this->escapeHtml($this->getImportDate()) ?>
<br/> var/amasty/geoip/GeoLite2-City-Blocks-IPv4.csv <img src="<?php echo $this->escapeHtml($this->getBlockImagePath()) ?>" />
<br/> var/amasty/geoip/GeoLite2-City-Blocks-IPv6.csv <img src="<?php echo $this->escapeHtml($this->getBlockV6ImagePath()) ?>" />
<br/> var/amasty/geoip/GeoLite2-City-Locations-en.csv <img src="<?php echo $this->escapeHtml($this->getLocationImagePath()) ?>" />
<br/>
<div class="progressbar">
    <div class="am_processer_container"><span class="begin"></span>

        <div class="am_line">
            <div class="am_processer" style="width: <?php echo (int)$this->getWidth() ?>%"><span>&nbsp</span></div>
        </div>
        <span class="<?php echo $this->getImportedClass() ?>"></span></div>
    <span class="import"><div class="bubble"><?php echo $this->escapeHtml($this->__("Import")) ?></div></span>
    <span class="completed"><div class="bubble"><?php echo $this->escapeHtml($this->__("Completed")) ?></div></span>
</div>