<?php
/**
 * @see PagarMe_Boleto_Block_Info_Boleto
 */
$helper = Mage::helper('pagarme_bowleto');
?>
<table id="pagarme_order_info_payment_details">
    <tr>
        <td class="label">
            <strong><?php echo $helper->__('Boleto Url'); ?></strong>
        </td>
        <td style="text-align: right" class="value">
            <a
                href="<?php echo $this->getBoletoUrl(); ?>"
                target="_blank"
            >
                <?php echo $helper->__('Show boleto'); ?>
            </a>
        </td>
    </tr>
</table>
