<?php
    $_code = $this->getMethodCode();
    $helper = Mage::helper('pagarme_creditcard');
?>

<div class="form-list" id="payment_form_<?= $_code ?>" style="display: none;">
    <input type="hidden" value="" name="payment[card_hash]" id="pagarme_card_hash" class="required_entry" />
    <input type="hidden" id="pagarme_encryption_key" value="<?= trim($this->getEncryptionKeyStoreConfig()); ?>">
    <div class="card-data">
        <div class="card-wrapper"></div>
        <ul>
            <li>
                <label for="<?= $_code ?>_creditcard_number" class="required">
                    <em>*</em><?= $helper->__('Credit Card Number') ?>
                </label>
                <div class="input-box">
                    <input
                        type="text"
                        id="<?= $_code ?>_creditcard_number"
                        title="<?= $helper->__('Credit Card Number') ?>"
                        class="input-text required-entry validate-alphanum-with-spaces validate-card-number-length"
                        maxlength="23"
                        value=""
                    />
                </div>
            </li>
            <li>
                <label for="<?= $_code ?>_creditcard_owner" class="required">
                    <em>*</em><?= $helper->__('Credit Card Owner') ?>
                </label>
                <div class="input-box">
                    <input
                        type="text"
                        id="<?= $_code ?>_creditcard_owner"
                        placeholder="<?= $helper->__('Name in credit card') ?>"
                        title="<?= $helper->__('Credit Card Owner') ?>"
                        class="input-text required-entry validate-alphanum-with-spaces validate-card-holder-length"
                        value=""
                    />
                </div>
            </li>
            <li>
                <label for="<?= $_code ?>_creditcard_expiration_date" class="required">
                    <em>*</em><?= $helper->__('Credit Card Expiration Date') ?>
                </label>
                <div class="input-box">
                    <input
                        type="text"
                        id="<?= $_code ?>_creditcard_expiration_date"
                        title="<?= $helper->__('Credit Card Expiration Date') ?>"
                        placeholder="MM / AAAA"
                        class="input-text required-entry validate-card-expiration-date"
                        maxlength="9"
                        value=""
                    />
                </div>
            </li>
            <li>
                <label for="<?= $_code ?>_creditcard_cvv" class="required">
                    <em>*</em><?= $helper->__('Credit Card Verification Number') ?>
                </label>
                <div class="input-box">
                    <input
                        type="text"
                        id="<?= $_code ?>_creditcard_cvv"
                        title="<?= $helper->__('Credit Card Verification Number') ?>"
                        class="input-text required-entry validate-digits validate-cvv-length"
                        maxlength="4"
                        value=""
                    />
                </div>
            </li>
            <li>
                <label for="<?= $_code ?>_creditcard_installments" class="required">
                    <em>*</em><?= $helper->__('Installments') ?>
                </label>
                <div class="input-box">
                    <select
                        name="payment[installments]"
                        id="<?= $_code ?>_creditcard_installments"
                        title="<?= $helper->__('Installments') ?>"
                        class="input-text required-entry validate-installments"
                    >
                    <option value="0">
                      <?= Mage::helper('pagarme_core')->__('Please, select the number of installments'); ?>
                    </option>
                    <?php foreach ($this->getInstallments() as $installmentNumber => $installmentInfo) : ?>
                        <option value="<?= $installmentNumber ?>">
                            <?php
                                $moduleHelper = Mage::helper('pagarme_core');
                                $floatInstallmentAmount = $moduleHelper
                                    ->parseAmountToCurrency(
                                        $installmentInfo['installment_amount']
                                    );
                                $floatInstallmentTotalAmount = $moduleHelper
                                    ->parseAmountToCurrency(
                                        $installmentInfo['total_amount']
                                );
                                if ((int)$installmentNumber <= $this->getFreeInstallmentsConfig()) {
                                    echo sprintf(
                                        '%sx R$ %s (sem juros)',
                                        $installmentNumber,
                                        number_format($floatInstallmentAmount, 2, ",", ".")
                                  );
                                } else {
                                    echo sprintf(
                                        '%sx R$ %s (total R$ %s)',
                                        $installmentNumber,
                                        number_format($floatInstallmentAmount, 2, ",", "."),
                                        number_format($floatInstallmentTotalAmount, 2, ",", ".")
                                  );
                                }
                            ?>
                        </option>
                    <?php endforeach; ?>
                    </select>
                </div>
            </li>
        </ul>
    </div>
</div>

<div>
    <?= $this->getMethod()->getConfigData('message');?>
</div>
<script type="text/javascript">
Translator.add('Please, enter a valid expiration date. For example 12 / 25.', "<?php echo $helper->__('Please, enter a valid expiration date. For example 12 / 25.'); ?>");
Translator.add('Please, enter a valid name.', "<?php echo $helper->__('Please, enter a valid name.'); ?>");
Translator.add('Please, enter a valid credit card number.', "<?php echo $helper->__('Please, enter a valid credit card number.'); ?>");
Translator.add('Please, enter a valid credit card verification number.', "<?php echo $helper->__('Please, enter a valid credit card verification number.'); ?>");
Translator.add('Please, select the number of installments.', "<?php echo $helper->__('Please, select the number of installments.'); ?>");

(function(window, document) {

  let generateCardHashEvent = false
  let card

  const findParentForm = node => {
    if (node.tagName === 'FORM') return node

    return findParentForm(node.parentNode)
  }

  const paymentDiv = document.querySelector('#payment_form_pagarme_creditcard')
  const checkoutForm = findParentForm(paymentDiv)

  if (!generateCardHashEvent) {
    checkoutForm.addEventListener('input', tryGenerateCardHash)

    generateCardHashEvent = true
  }

  const loadCardScript = () => {
    let cardScript = document.createElement('script');
    cardScript.setAttribute('src', 'https://s3.amazonaws.com/card.prd.pagarme.net/card.js')
    cardScript.setAttribute('id', 'cardScript')

    document.body.appendChild(cardScript)

    cardScript.addEventListener('load', createCard)
  }

  const createCard = () => {
    if (!card) {
      if (paymentDiv.parentElement.getWidth() < 600) {
        const cardDataDiv = document.querySelector('.card-data')
        cardDataDiv.addClassName('card-data-column')
      }

      card = new Card({
        form: checkoutForm,
        container: '.card-wrapper',
        formSelectors: {
            numberInput: 'input[id="pagarme_creditcard_creditcard_number"]',
            expiryInput: 'input[id="pagarme_creditcard_creditcard_expiration_date"]',
            cvcInput: 'input[id="pagarme_creditcard_creditcard_cvv"]',
            nameInput: 'input[id="pagarme_creditcard_creditcard_owner"]',
        },

        formatting: true,
        debug: false
      });
    }
  }

  const hasCardScriptLoaded = document.querySelector('#cardScript')
  if (!hasCardScriptLoaded) {
    loadCardScript()
  } else {
    createCard()
  }
}(window, document))
</script>
