<?php
$logo_path = Mage::getStoreConfig('design/header/logo_src');
$logo_src = $this->getSkinUrl().'/'.$logo_path;
$logo_alt = Mage::getStoreConfig('design/header/logo_alt');
?>

<div id="topnav">
    <div class="container">
        <div class="row">
            <div class="quicktop-wrapper">
                <div class="menuicon">
                    <i></i>
                    <i></i>
                    <i></i>
                </div>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $logo_alt ?>" class="logo"><img src="<?php echo $logo_src; ?>" alt="<?php echo $logo_alt ?>" /></a>
                <?php echo $this->getChildHtml('cart_sidebar') ?>
            </div>
        </div>
    </div>
</div>