<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Scheckout
 */
?>
<?php
    /** @var Amasty_Scheckout_Block_Visualoptions $this */

    $backgroundColor = '#FFF'; //bg

    $fontFamily = $this->getFontFamily();

    $textColor = $this->getTextColor();
    $themeColor = $this->getThemeColor();
    $themeColorTo = $this->colourBrightness($themeColor, -0.7);
    $themeColorFrom = $this->colourBrightness($themeColor, 0.9);

    $buttonColor = $this->getButtonColor();
    $buttonBorderColor = $this->colourBrightness($buttonColor, -0.8);
    $buttonColorFrom = $this->colourBrightness($buttonColor, -0.8);
    $buttonColorTo = $this->colourBrightness($buttonColor, 1);

    $buttonColorActiveFrom = $this->colourBrightness($buttonColor, 1);
    $buttonColorActiveTo = $this->colourBrightness($buttonColor, -0.8);

    $buttonColorHoverFrom = $this->colourBrightness($buttonColorFrom, 0.9);
    $buttonColorHoverTo = $this->colourBrightness($buttonColorTo, 0.9);
?>
<style>

    .amscheckout-main {
        border: 2px solid <?php echo $themeColor?>;
        background-color: <?php echo $backgroundColor?>;
        color: <?php echo $textColor?>;
    }

    <?php if ($this->isSetFontFamily()): ?>
    .amscheckout-main,
    .amschekcout_title,
    .amschekcout_content {
        font-family: <?php echo $fontFamily;?>;
    }
    <?php endif; ?>

    .amscheckout-login-table label,
    .amscheckout .form-list label,
    .amscheckout .amscheckout-label {
        color: <?php echo $textColor?>;
    }

    .amscheckout-main a,
    .amscheckout-main a:active,
    .amscheckout-main a:hover,
    .amscheckout-login a,
    .amscheckout-login a:active,
    .amscheckout-login a:hover {
        color: <?php echo $themeColor?>;
    }

    .amscheckout textarea:focus,
    .amscheckout select:focus,
    .amscheckout-login input[type="text"]:focus,
    .amscheckout input[type="text"]:focus,
    .amscheckout select:focus:hover,
    .amscheckout-login input[type="text"]:focus:hover,
    .amscheckout textarea:focus:hover,
    .amscheckout input[type="text"]:focus:hover {
        box-shadow: 0px 0px 5px <?php echo $themeColor?>;
        border: 1px solid <?php echo $themeColor?>;
    }

    .amscheckout .form-list label.required em,
    .amscheckout .amscheckout-label em {
        color: <?php echo $themeColor?>;
    }

    .amscheckout-login {
        border: 2px solid <?php echo $themeColor?>;
        background-color: <?php echo $backgroundColor?>;
    }

    .amscheckout-img {
        background-color: <?php echo $themeColor;?>;
        background-image: linear-gradient(to top, <?php echo $themeColorFrom;?>, <?php echo $themeColorTo;?>);
    }

    .amschekcout_title {
        background-color: <?php echo $themeColor;?>;
        background-image: linear-gradient(to top, <?php echo $themeColorFrom;?>, <?php echo $themeColorTo;?>);
    }

    .amscheckout-img-shadow {
        background-color: <?php echo $backgroundColor?>;
        background-image: linear-gradient(99deg, #000,<?php echo $backgroundColor?>);
    }

    .amscheckout-tab-guest-checkout, .amscheckout-tab-login {
        background-color: <?php echo $buttonColor?>;
    }

    .amscheckout-dologin:active span,
    .amscheckout-submit:active span,
    .amscheckout-apply:active span {
        background-color: <?php echo $buttonColor?>;
        border: solid 1px <?php echo $buttonBorderColor;?>;
        background-image: linear-gradient(to top, <?php echo $buttonColorActiveFrom;?>, <?php echo $buttonColorActiveTo;?>);
    }

    .amscheckout-dologin:hover span,
    .amscheckout-submit:hover span,
    .amscheckout-apply:hover span {
        background-color: <?php echo $buttonColor?>;
        box-shadow: 0 3px 3px rgba(0, 0, 0, .25), inset 0 0 3px rgba(255, 255, 255, .89);
        border: solid 1px <?php echo $buttonBorderColor;?>;
        background-image: linear-gradient(to top, <?php echo $buttonColorHoverFrom;?>, <?php echo $buttonColorHoverTo;?>);
    }

    .amscheckout-dologin span,
    .amscheckout-submit span,
    .amscheckout-apply span {
        background-color: <?php echo $buttonColor?>;
        box-shadow: 0 3px 3px rgba(0, 0, 0, .25), inset 0 0 3px rgba(255, 255, 255, .89);
        border: solid 1px <?php echo $buttonBorderColor;?>;
        background-image: linear-gradient(to top, <?php echo $buttonColorFrom;?>, <?php echo $buttonColorTo;?>);
    }

</style>