<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 *The Split Options Request
 */
class CreateSplitOptionsRequest implements JsonSerializable
{
    /**
     * Liable options
     * @var bool|null $liable public property
     */
    public $liable;

    /**
     * Charge processing fee
     * @maps charge_processing_fee
     * @var bool|null $chargeProcessingFee public property
     */
    public $chargeProcessingFee;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool $liable              Initialization value for $this->liable
     * @param bool $chargeProcessingFee Initialization value for $this->chargeProcessingFee
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->liable              = func_get_arg(0);
            $this->chargeProcessingFee = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['liable']                = $this->liable;
        $json['charge_processing_fee'] = $this->chargeProcessingFee;

        return $json;
    }
}
