<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 *Request for canceling a charge.
 */
class CreateCancelChargeRequest implements JsonSerializable
{
    /**
     * The amount that will be canceled.
     * @var integer|null $amount public property
     */
    public $amount;

    /**
     * The split rules request
     * @maps split_rules
     * @var \MundiAPILib\Models\CreateCancelChargeSplitRulesRequest[]|null $splitRules public property
     */
    public $splitRules;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $amount     Initialization value for $this->amount
     * @param array   $splitRules Initialization value for $this->splitRules
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->amount     = func_get_arg(0);
            $this->splitRules = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['amount']      = $this->amount;
        $json['split_rules'] = $this->splitRules;

        return $json;
    }
}
