<?php
/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MundiAPILib\Models;

use JsonSerializable;

/**
 *Request for capturing a charge
 */
class CreateCaptureChargeRequest implements JsonSerializable
{
    /**
     * Code for the charge. Sending this field will update the code send on the charge and order creation.
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * The amount that will be captured
     * @var integer|null $amount public property
     */
    public $amount;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $code   Initialization value for $this->code
     * @param integer $amount Initialization value for $this->amount
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->code   = func_get_arg(0);
            $this->amount = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']   = $this->code;
        $json['amount'] = $this->amount;

        return $json;
    }
}
